### ISSUE TITLE
Add fasta/q files with long IDs

### ISSUE THREAD

**Issue by audy** [omgenomics/bio-data-zoo#4]
This is something that I have encountered in the wild. They are valid files AFAIK but they can [lead to samtools breaking](https://github.com/samtools/samtools/issues/1081) (e.g., `minimap2 ... long-ids.fastq | samtools`).

**Comment by robertaboukhalil** [comment]
Thanks @audy, this is great, I did not know that read names were limited to 254 characters!

**Comment by robertaboukhalil** [comment]
Added it in https://github.com/omgenomics/bio-data-zoo/commit/f23be65c2d21110113d275b8364388c458e395c4, thanks again!
